[project]
name = "media-sorter"
version = "0.1.0"
description = "Personal script to sort media files into folders based on their metadata."
authors = [
    {name = "nasquier"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    # "mutagen (>=1.46.0,<2.0.0)",
    "Pillow (>=10.0.0,<11.0.0)",
    # "tqdm (>=4.66.1,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
dev = [
    "pytest (>=8.4.2,<9.0.0)",
    "pytest-asyncio (>=1.2.0,<2.0.0)",
    "flake8 (>=7.0.0,<8.0.0)",
    "black (>=24.0.0,<25.0.0)",
    "debugpy (>=1.8.17,<2.0.0)"
]

[tool.black]
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

[tool.flake8]
max-line-length = 88
extend-ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", ".venv", ".pytest_cache"]
